# .do/app.yaml
name: afilia-backend
region: lon1

alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED

features:
  - buildpack-stack=ubuntu-22

services:
  - name: api
    environment_slug: node-js
    run_command: npm start
    http_port: 8070
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-1gb
    source_dir: backend/
    github:
      repo: aminemn14/afilia
      branch: main
      deploy_on_push: false # on désactive l’auto-déploy, on passe par GH Actions
    env:
      DO_SPACES_ENDPOINT: ${DO_SPACES_ENDPOINT}
      DO_SPACES_BUCKET: ${DO_SPACES_BUCKET}
      DO_ACCESS_KEY: ${DO_ACCESS_KEY}
      DO_SECRET_KEY: ${DO_SECRET_KEY}

ingress:
  rules:
    - component:
        name: api
      match:
        path:
          prefix: /
