# .do/app.yaml
name: afilia-backend
region: lon1

alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED

features:
  - buildpack-stack=ubuntu-22

services:
  - name: api
    environment_slug: node-js
    run_command: npm start
    http_port: 8070
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-1gb
    source_dir: backend/
    github:
      repo: aminemn14/afilia
      branch: main
      deploy_on_push: false
    envs:
      - key: MONGO_URI
        scope: RUN_TIME
        value: ${MONGO_URI}
      - key: PORT
        scope: RUN_TIME
        value: ${PORT}
      - key: MESSAGE_SECRET
        scope: RUN_TIME
        value: ${MESSAGE_SECRET}
      - key: DO_ACCESS_KEY
        scope: RUN_TIME
        value: ${DO_ACCESS_KEY}
      - key: DO_SECRET_KEY
        scope: RUN_TIME
        value: ${DO_SECRET_KEY}
      - key: DO_SPACES_ENDPOINT
        scope: RUN_TIME
        value: ${DO_SPACES_ENDPOINT}
      - key: DO_SPACES_BUCKET
        scope: RUN_TIME
        value: ${DO_SPACES_BUCKET}

ingress:
  rules:
    - component:
        name: api
      match:
        path:
          prefix: /
