const cardBackgrounds: { [key: number]: any } = {
  1: require('@/assets/images/card-background/1.jpeg'),
  2: require('@/assets/images/card-background/2.jpeg'),
  3: require('@/assets/images/card-background/3.jpeg'),
  4: require('@/assets/images/card-background/4.jpeg'),
  5: require('@/assets/images/card-background/5.jpeg'),
  6: require('@/assets/images/card-background/6.jpeg'),
  7: require('@/assets/images/card-background/7.jpeg'),
  8: require('@/assets/images/card-background/8.jpeg'),
  9: require('@/assets/images/card-background/9.jpeg'),
  10: require('@/assets/images/card-background/10.jpeg'),
  11: require('@/assets/images/card-background/11.jpeg'),
  12: require('@/assets/images/card-background/12.jpeg'),
  13: require('@/assets/images/card-background/13.jpeg'),
  14: require('@/assets/images/card-background/14.jpeg'),
  15: require('@/assets/images/card-background/15.jpeg'),
  16: require('@/assets/images/card-background/16.jpeg'),
  17: require('@/assets/images/card-background/17.jpeg'),
  18: require('@/assets/images/card-background/18.jpeg'),
  19: require('@/assets/images/card-background/19.jpeg'),
  20: require('@/assets/images/card-background/20.jpeg'),
  21: require('@/assets/images/card-background/21.jpeg'),
  22: require('@/assets/images/card-background/22.jpeg'),
  23: require('@/assets/images/card-background/23.jpeg'),
  24: require('@/assets/images/card-background/24.jpeg'),
  25: require('@/assets/images/card-background/25.jpeg'),
};

export default cardBackgrounds;
